parameters: 
    categories: 
        C01: Catéagorie 1
        C02: Catéagorie 2
        C03: Catéagorie 3
#    question_type:
#        0: Texte libre
#        1: Radio
#        2: Checkbox
#        3: Combobox
    question_has_score : false
    question_has_condition: false
    question_has_help: false
    extra_response: false
    quiz_front : false
    quiz_subject:
        class: quizFrontBundle:Application
        entity: quiz\FrontBundle\Entity\Application

           